# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PiplinePlanner
                                 A QGIS plugin
 Allow the user to create a line and evaliate impacts
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-23
        copyright            : (C) 2026 by Sebastian Sturm
        email                : sebastian.sturm@geosturm.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PiplinePlanner class from file PiplinePlanner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pipeline_planner import PiplinePlanner
    return PiplinePlanner(iface)
